# Generated by Django 4.0.3 on 2022-03-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auctions',
            fields=[
                ('Pid', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField(max_length=255, null=True)),
                ('date', models.IntegerField(max_length=55, null=True)),
                ('allocations', models.JSONField(null=True)),
                ('catalogue', models.JSONField(null=True)),
                ('invoices', models.JSONField(null=True)),
            ],
        ),
    ]
