# Generated by Django 4.0.3 on 2022-03-16 14:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctions',
            name='date',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999999999999999999999)]),
        ),
        migrations.AlterField(
            model_name='auctions',
            name='number',
            field=models.CharField(max_length=55, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
        ),
    ]
