# Generated by Django 4.0.3 on 2022-03-17 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_auctions_date_alter_auctions_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctions',
            name='catalogue_closing_date',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='auctions',
            name='prompt_date',
            field=models.CharField(max_length=55, null=True),
        ),
    ]
