# Generated by Django 4.0.3 on 2022-03-17 08:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auctions_catalogue_closing_date_auctions_prompt_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctions',
            name='year',
            field=models.CharField(max_length=25, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
        ),
        migrations.AlterField(
            model_name='auctions',
            name='date',
            field=models.CharField(max_length=55, null=True),
        ),
    ]
