# Generated by Django 4.0.3 on 2022-03-17 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auctions_year_alter_auctions_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctions',
            name='catalogue_closing_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='auctions',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='auctions',
            name='prompt_date',
            field=models.DateField(null=True),
        ),
    ]
