# Generated by Django 4.0.3 on 2022-03-23 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auctions_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctions',
            name='catalogue_data',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='auctions',
            name='invoice_data',
            field=models.JSONField(null=True),
        ),
    ]
