# Generated by Django 4.0.3 on 2022-03-24 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auctions_catalogue_data_auctions_invoice_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctions',
            name='catalogue_data',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='auctions',
            name='invoice_data',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
