# Generated by Django 4.0.3 on 2022-03-28 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_auctions_catalogue_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctions',
            name='invoice_number',
            field=models.IntegerField(default=0, max_length=55),
        ),
    ]
