# Generated by Django 4.0.3 on 2022-03-28 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_auctions_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctions',
            name='invoice_number',
            field=models.IntegerField(default=1),
        ),
    ]
