# Generated by Django 4.0.4 on 2022-04-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auctions_account_sale_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarksOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='marks_order', max_length=55)),
                ('order', models.JSONField(default='{"SIOMO":1,"EMROK":1,"TULON": true,"SARMA":1,"TEGAT":1,"CUPATEA":1,"KABIANGA":1,"KIPSINENDE":1,"SIAN":1}')),
            ],
        ),
    ]
