# Generated by Django 4.0.4 on 2022-04-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_marksorder_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outlots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='outlots_list', max_length=55)),
                ('outlots', models.JSONField(null=True)),
            ],
        ),
    ]
