# Generated by Django 4.0.4 on 2022-04-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_outlots'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctions',
            name='outlots',
            field=models.JSONField(null=True),
        ),
    ]
