# Generated by Django 4.0.4 on 2022-05-08 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auctions_outlots'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctions',
            name='warehouse_confirmation_data',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='auctions',
            name='warehouse_confirmation_number',
            field=models.IntegerField(default=1),
        ),
    ]
